Repository pivotal-cf/docs-pas, pull requests merged in 2020-10, with the labels that each got.

#26 Tracker integration test
  README.md
Labels: unscheduled

#31 Add Apps Manager release notes for TAS 2.10.5
  release-notes/runtime-rn.html.md.erb
Labels: in progress

#32 Add Apps Manager release notes for TAS 2.11.0-alpha.10
  release-notes/runtime-rn.html.md.erb
Labels: in progress

#28 Add Apps Manager release notes for PAS 2.7.25
  release-notes/runtime-rn.html.md.erb
Labels: in progress

#29 Add Apps Manager release notes for PAS 2.8.19
  release-notes/runtime-rn.html.md.erb
Labels: in progress

#30 Add Apps Manager release notes for TAS 2.9.13
  release-notes/runtime-rn.html.md.erb
Labels: in progress

#27 qualify Rolling App Deployments GA
  release-notes/runtime-rn.html.md.erb
Labels: scheduled

#34 add known issues regarding metric registrar 1.2.1 -- 2.7
  release-notes/runtime-rn.html.md.erb
Labels: in progress

#35 add known issues regarding metric registrar 1.2.1 -- 2.8
  release-notes/runtime-rn.html.md.erb
Labels: in progress

#36 add known issues regarding metric registrar 1.2.1 -- 2.9
  release-notes/runtime-rn.html.md.erb
Labels: in progress

#37 add known issues regarding metric registrar 1.2.1 -- 2.10
  release-notes/runtime-rn.html.md.erb
Labels: in progress

#38 Fix usage service release note links
  release-notes/runtime-rn.html.md.erb
Labels: in progress
