Repository pivotal-cf/docs-pas, pull requests merged in 2022-10, with the labels that each got.

#206 Add known issues for Jammy compatibility to TAS 3.0 release notes
  runtime-rn.html.md.erb
Labels: scheduled

#207 breaking change: HAProxy Removed
  runtime-rn.html.md.erb
  segment-rn.html.md.erb
Labels: in progress

#211 Document new log rate limiting feature
  runtime-rn.html.md.erb
Labels: unscheduled

#212 Don't link to Admin or Operating Guides in TAS offline docs
  runtime-rn.html.md.erb
Labels: unscheduled

#213 Don't link to Admin or Operating Guides in TAS offline docs
  segment-rn.html.md.erb
Labels: unscheduled
